services:
  db:
    image: ${IMAGE_MYSQL}
    container_name: ${CONTAINER_NAME}_db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - network

  wordpress:
    depends_on:
      - db
    image: ${IMAGE_WORDPRESS}
    container_name: ${CONTAINER_NAME}_wordpress
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./conf.d/upload.ini:/usr/local/etc/php/conf.d/upload.ini
      - wordpress_data:/var/www/html
    ports:
      - "${PORT_WORDPRESS}:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG}
    networks:
      - network

  phpmyadmin:
    depends_on:
      - db
    image: ${IMAGE_PHPMYADMIN}
    container_name: ${CONTAINER_NAME}_phpmyadmin
    ports:
      - "${PORT_PHPMYADMIN}:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: wordpress
    networks:
      - network

volumes:
  db_data:
    name: ${CONTAINER_NAME}_db_data
  wordpress_data:
    name: ${CONTAINER_NAME}_wordpress_data

networks:
  network:
    name: ${CONTAINER_NAME}_network