version: '3.9'
services:
  db:
    image: mysql:${IMAGE_TAG_MYSQL}
    container_name: ${CONTAINER_NAME}_db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1s
      timeout: 2s
      retries: 10

  wordpress:
    depends_on:
      db:
        condition: service_healthy
    image: wordpress:${IMAGE_TAG_WORDPRESS}
    container_name: ${CONTAINER_NAME}_wordpress
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./conf.d/upload.ini:/usr/local/etc/php/conf.d/upload.ini
      - type: volume
        source: wordpress_data
        target: /var/www/html
    ports:
      - "${PORT_WORDPRESS}:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG}
    networks:
      - network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:${IMAGE_TAG_PHPMYADMIN}
    container_name: ${CONTAINER_NAME}_phpmyadmin
    ports:
      - "${PORT_PHPMYADMIN}:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: wordpress
    networks:
      - network

volumes:
  db_data:
    name: ${CONTAINER_NAME}_db_data
  wordpress_data:
    name: ${CONTAINER_NAME}_wordpress_data

networks:
  network:
    name: ${CONTAINER_NAME}_network