version: '3.9'

services:
  db:
    image: mysql:${MYSQL_IMAGE_TAG}
    container_name: ${CONTAINER_NAME}_db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - ${IP_ADDRESS}:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - network

  wordpress:
    depends_on:
      - db
    image: wordpress:${WORDPRESS_IMAGE_TAG}
    container_name: ${CONTAINER_NAME}_wordpress
    volumes:
      - .:/var/www/html/wp-content
      - type: volume
        source: wordpress_data
        target: /var/www/html
    ports:
      - "${IP_ADDRESS}:80:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG : ${WORDPRESS_DEBUG}
    networks:
      - network

volumes:
  db_data:
    name: ${CONTAINER_NAME}_db_data
  wordpress_data:
    name: ${CONTAINER_NAME}_wordpress_data
networks:
  network:
    name: ${CONTAINER_NAME}_network